apiVersion: v1
kind: Namespace
metadata:
  name: <namespace>

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: kraken
  namespace: <namespace>

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole

metadata:
  name: kraken-role

rules:
  - apiGroups: [""]
    resources: ["nodes", "services", "pods", "endpoints", "namespaces"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["create", "delete"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding

metadata:
  name: kraken-crb

roleRef:
  kind: ClusterRole
  name: kraken-role
  apiGroup: rbac.authorization.k8s.io

subjects:
  - kind: ServiceAccount
    name: kraken
    namespace: <namespace>